apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-php
#          image: php:7.1.24-fpm-alpine3.8
          image: hermsi/alpine-fpm-php:7.1
          volumeMounts:
            - mountPath: /var/www/html
              name: app-volume
            - mountPath: /tmp/config
              name: sample-php-config
          command:
            - sh
            - "-c"
            - |
              cp /tmp/config/php.ini /usr/local/etc/php/php.ini
              /usr/local/sbin/php-fpm
          env:
            - name: MYSQL_ADDR
              value: mysql-service.default.svc.cluster.local
            - name: PHINX_MYSQL_ADDR
              value: mysql-service.default.svc.cluster.local

          ports:
            - containerPort: 9000
        - name: sample-nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /tmp/config
              readOnly: true
              name: sample-nginx-config
          command:
            - sh
            - "-c"
            - |
              cp /tmp/config/nginx.conf /etc/nginx/nginx.conf
              cp /tmp/config/default.conf /etc/nginx/conf.d/default.conf
              nginx -g "daemon off;"
        - name: memcached
          image: memcached:alpine
          ports:
            - containerPort: 11211
      volumes:
        - name: sample-nginx-config
          configMap:
            name: sample-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: default.conf
                path: default.conf
        - name: sample-php-config
          configMap:
            name: sample-php-config
            items:
              - key: php.ini
                path: php.ini
        - name: app-volume
          hostPath:
            path: /Users/deadcode/sample_kube_local/app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

